# Site settings
title: Mobile Development Group, IIT Roorkee
email: sdsmdg@gmail.com
description: Where ideas meet reality

url: "http://mdg.sdslabs.co/" # the base hostname & protocol for your site


#Google Ad Words Data from scripts code (using Google responsive options) and ad client
data-ad-slot: 
data-ad-client: 
google_ad_client: 
google_analytics: 
addthis_id: 

# Social networks usernames (many more available: flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.) see all icon at fontawesome.io
social:
#  - title: twitter
  - title: facebook
    url: https://facebook.com/mdgiitr
  - title: google-plus
    url: https://plus.google.com/mobiledevelopmentgroup
  - title: github
    url: http://github.com/sdsmdg
  - title: envelope
    url: mailto:sdsmdg@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

plugins: [jekyll-paginate, jekyll-feed]
# Build settings
