# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Where ideas meet reality! 
name: Mobile Development Group # ex. DONGChuan
email: sdsmdg@gmail.com
location: Indian Institute of Technology, Roorkee # ex. Nice, France
company: SDS Labs
company_url: https://sdslabs.co/
github_url: https://github.com/sdsmdg # ex. https://github.com/DONGChuan
description: Jekyll powered web application for SDS Mobile Development Group, IIT Roorkee.
favicon: favicon.png # Image must be in assets/images
repository: sdsmdg/sdsmdg.github.io # ex. DONGChuan/DONGChuan.github.io

# The base hostname & protocol for your site
# For local test, please use http://localhost:4000
# For production, use your github page url. ex. http://dongchuan.github.io
url: http://sdsmdg.github.io
# url: 172.25.12.109:4000

## Gem
gems:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true

# Disque
disque: my_disque_settings # ex. httpdongchuangithubio.disqus.com

# Pagination
paginate: 5
paginate_path: 'page:num'

# Navigation. If you do not like these modules, just remove them :D
navs:
  -
    href: /
    label: Home

  # -
  #   href: /open-source
  #   label: Open-Source

  -
    href: /blog
    label: Blog

  -
    href: /bookmark
    label: Bookmarks

  -
    href: /about
    label: About

# Sidebar to show popular repo
side_bar_repo_limit: 5 # Number of repos to show

# Google Analytics
analytics :
  provider : google
  google :
      tracking_id : 'tracking_id'  # ex. UA-72165600-X
